/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversalCalcsRouteImport } from './routes/universal-calcs'
import { Route as NeuronMetricsRouteImport } from './routes/neuron-metrics'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as CalmSpaceRouteImport } from './routes/calm-space'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalmMindfulRouteImport } from './routes/calm.mindful'
import { Route as CalmFocusRouteImport } from './routes/calm.focus'
import { Route as CalmBreathRouteImport } from './routes/calm.breath'
import { Route as CalmAmbientRouteImport } from './routes/calm.ambient'
import { Route as CalcsPhysicsRouteImport } from './routes/calcs.physics'
import { Route as CalcsMathematicsRouteImport } from './routes/calcs.mathematics'
import { Route as CalcsHealthRouteImport } from './routes/calcs.health'
import { Route as CalcsAccountsRouteImport } from './routes/calcs.accounts'

const UniversalCalcsRoute = UniversalCalcsRouteImport.update({
  id: '/universal-calcs',
  path: '/universal-calcs',
  getParentRoute: () => rootRouteImport,
} as any)
const NeuronMetricsRoute = NeuronMetricsRouteImport.update({
  id: '/neuron-metrics',
  path: '/neuron-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CalmSpaceRoute = CalmSpaceRouteImport.update({
  id: '/calm-space',
  path: '/calm-space',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalmMindfulRoute = CalmMindfulRouteImport.update({
  id: '/calm/mindful',
  path: '/calm/mindful',
  getParentRoute: () => rootRouteImport,
} as any)
const CalmFocusRoute = CalmFocusRouteImport.update({
  id: '/calm/focus',
  path: '/calm/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const CalmBreathRoute = CalmBreathRouteImport.update({
  id: '/calm/breath',
  path: '/calm/breath',
  getParentRoute: () => rootRouteImport,
} as any)
const CalmAmbientRoute = CalmAmbientRouteImport.update({
  id: '/calm/ambient',
  path: '/calm/ambient',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcsPhysicsRoute = CalcsPhysicsRouteImport.update({
  id: '/calcs/physics',
  path: '/calcs/physics',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcsMathematicsRoute = CalcsMathematicsRouteImport.update({
  id: '/calcs/mathematics',
  path: '/calcs/mathematics',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcsHealthRoute = CalcsHealthRouteImport.update({
  id: '/calcs/health',
  path: '/calcs/health',
  getParentRoute: () => rootRouteImport,
} as any)
const CalcsAccountsRoute = CalcsAccountsRouteImport.update({
  id: '/calcs/accounts',
  path: '/calcs/accounts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calm-space': typeof CalmSpaceRoute
  '/insights': typeof InsightsRoute
  '/neuron-metrics': typeof NeuronMetricsRoute
  '/universal-calcs': typeof UniversalCalcsRoute
  '/calcs/accounts': typeof CalcsAccountsRoute
  '/calcs/health': typeof CalcsHealthRoute
  '/calcs/mathematics': typeof CalcsMathematicsRoute
  '/calcs/physics': typeof CalcsPhysicsRoute
  '/calm/ambient': typeof CalmAmbientRoute
  '/calm/breath': typeof CalmBreathRoute
  '/calm/focus': typeof CalmFocusRoute
  '/calm/mindful': typeof CalmMindfulRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calm-space': typeof CalmSpaceRoute
  '/insights': typeof InsightsRoute
  '/neuron-metrics': typeof NeuronMetricsRoute
  '/universal-calcs': typeof UniversalCalcsRoute
  '/calcs/accounts': typeof CalcsAccountsRoute
  '/calcs/health': typeof CalcsHealthRoute
  '/calcs/mathematics': typeof CalcsMathematicsRoute
  '/calcs/physics': typeof CalcsPhysicsRoute
  '/calm/ambient': typeof CalmAmbientRoute
  '/calm/breath': typeof CalmBreathRoute
  '/calm/focus': typeof CalmFocusRoute
  '/calm/mindful': typeof CalmMindfulRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calm-space': typeof CalmSpaceRoute
  '/insights': typeof InsightsRoute
  '/neuron-metrics': typeof NeuronMetricsRoute
  '/universal-calcs': typeof UniversalCalcsRoute
  '/calcs/accounts': typeof CalcsAccountsRoute
  '/calcs/health': typeof CalcsHealthRoute
  '/calcs/mathematics': typeof CalcsMathematicsRoute
  '/calcs/physics': typeof CalcsPhysicsRoute
  '/calm/ambient': typeof CalmAmbientRoute
  '/calm/breath': typeof CalmBreathRoute
  '/calm/focus': typeof CalmFocusRoute
  '/calm/mindful': typeof CalmMindfulRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calm-space'
    | '/insights'
    | '/neuron-metrics'
    | '/universal-calcs'
    | '/calcs/accounts'
    | '/calcs/health'
    | '/calcs/mathematics'
    | '/calcs/physics'
    | '/calm/ambient'
    | '/calm/breath'
    | '/calm/focus'
    | '/calm/mindful'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calm-space'
    | '/insights'
    | '/neuron-metrics'
    | '/universal-calcs'
    | '/calcs/accounts'
    | '/calcs/health'
    | '/calcs/mathematics'
    | '/calcs/physics'
    | '/calm/ambient'
    | '/calm/breath'
    | '/calm/focus'
    | '/calm/mindful'
  id:
    | '__root__'
    | '/'
    | '/calm-space'
    | '/insights'
    | '/neuron-metrics'
    | '/universal-calcs'
    | '/calcs/accounts'
    | '/calcs/health'
    | '/calcs/mathematics'
    | '/calcs/physics'
    | '/calm/ambient'
    | '/calm/breath'
    | '/calm/focus'
    | '/calm/mindful'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalmSpaceRoute: typeof CalmSpaceRoute
  InsightsRoute: typeof InsightsRoute
  NeuronMetricsRoute: typeof NeuronMetricsRoute
  UniversalCalcsRoute: typeof UniversalCalcsRoute
  CalcsAccountsRoute: typeof CalcsAccountsRoute
  CalcsHealthRoute: typeof CalcsHealthRoute
  CalcsMathematicsRoute: typeof CalcsMathematicsRoute
  CalcsPhysicsRoute: typeof CalcsPhysicsRoute
  CalmAmbientRoute: typeof CalmAmbientRoute
  CalmBreathRoute: typeof CalmBreathRoute
  CalmFocusRoute: typeof CalmFocusRoute
  CalmMindfulRoute: typeof CalmMindfulRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universal-calcs': {
      id: '/universal-calcs'
      path: '/universal-calcs'
      fullPath: '/universal-calcs'
      preLoaderRoute: typeof UniversalCalcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neuron-metrics': {
      id: '/neuron-metrics'
      path: '/neuron-metrics'
      fullPath: '/neuron-metrics'
      preLoaderRoute: typeof NeuronMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calm-space': {
      id: '/calm-space'
      path: '/calm-space'
      fullPath: '/calm-space'
      preLoaderRoute: typeof CalmSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calm/mindful': {
      id: '/calm/mindful'
      path: '/calm/mindful'
      fullPath: '/calm/mindful'
      preLoaderRoute: typeof CalmMindfulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calm/focus': {
      id: '/calm/focus'
      path: '/calm/focus'
      fullPath: '/calm/focus'
      preLoaderRoute: typeof CalmFocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calm/breath': {
      id: '/calm/breath'
      path: '/calm/breath'
      fullPath: '/calm/breath'
      preLoaderRoute: typeof CalmBreathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calm/ambient': {
      id: '/calm/ambient'
      path: '/calm/ambient'
      fullPath: '/calm/ambient'
      preLoaderRoute: typeof CalmAmbientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcs/physics': {
      id: '/calcs/physics'
      path: '/calcs/physics'
      fullPath: '/calcs/physics'
      preLoaderRoute: typeof CalcsPhysicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcs/mathematics': {
      id: '/calcs/mathematics'
      path: '/calcs/mathematics'
      fullPath: '/calcs/mathematics'
      preLoaderRoute: typeof CalcsMathematicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcs/health': {
      id: '/calcs/health'
      path: '/calcs/health'
      fullPath: '/calcs/health'
      preLoaderRoute: typeof CalcsHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calcs/accounts': {
      id: '/calcs/accounts'
      path: '/calcs/accounts'
      fullPath: '/calcs/accounts'
      preLoaderRoute: typeof CalcsAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalmSpaceRoute: CalmSpaceRoute,
  InsightsRoute: InsightsRoute,
  NeuronMetricsRoute: NeuronMetricsRoute,
  UniversalCalcsRoute: UniversalCalcsRoute,
  CalcsAccountsRoute: CalcsAccountsRoute,
  CalcsHealthRoute: CalcsHealthRoute,
  CalcsMathematicsRoute: CalcsMathematicsRoute,
  CalcsPhysicsRoute: CalcsPhysicsRoute,
  CalmAmbientRoute: CalmAmbientRoute,
  CalmBreathRoute: CalmBreathRoute,
  CalmFocusRoute: CalmFocusRoute,
  CalmMindfulRoute: CalmMindfulRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
